# Generated by Django 5.0.3 on 2024-06-10 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('year_batch', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=50)),
                ('cp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('order_date_time', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.customer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('oid', models.AutoField(primary_key=True, serialize=False)),
                ('paid_status', models.BooleanField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_date_time', models.DateTimeField(auto_now=True)),
                ('cid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.customer')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dd.inventory')),
            ],
        ),
    ]
