# Generated by Django 5.0.6 on 2024-06-12 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
