# Generated by Django 5.0.6 on 2024-06-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0002_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='level',
            field=models.IntegerField(default=2),
        ),
    ]
