# Generated by Django 5.0.6 on 2024-06-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dd', '0003_customer_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default='', max_length=120),
        ),
    ]
